trk/ios/Podfile.lock
trk/ios/trk/Info.plist
trk/package-lock.json
trk/package.json
trk/src/Screens/ClimbList/index.js
trk/yarn.lock

<h3>This adds an onPress handler to the pre-existing image upload button which utilises a component from imagePicker library to access user's photo album and choose a photo to upload. This photo gets uploaded to firebase storage upon write, with as its file name the climb document id. The climb document does not yet received this storage pathway as the key-value pair for image (this will be done in next PR)</h3>
This is the documentation for the react-native-image-crop-picker https://github.com/ivpusic/react-native-image-crop-picker
https://github.com/nagimonyc/trk-app/assets/126114238/90f745a8-f8f3-478b-a7cf-b7db1539fef3

[GEN-161] Allow routesetters to upload image to firebase storage when writing a climb

---

trk/src/Screens/ClimbDetail/index.js

Made if/else statement so that if climb set = 'Competition', the climbdetail returned is different than for commercial boulder. Side by side view for the read of a climb with set = "Commercial" and set = "Competition"

[GEN-174] Skeleton structure of the climb detail view for the competition

---

trk/src/Components/ClimbItem.js
trk/src/Components/SetterProfile.js
trk/src/Navigation/AppNavigator.js
trk/src/Screens/SetDetail/index.js

Create a new screen called SetDetail, added it to AppNav in the ProfileStack, made SetterProfile pass down the climb document id in its props, built SetDetail to show climb grade, name, setter photo (saved in storage, always marcial), and the climb photo (individual storage path saved in climb document field called 'photo', if no 'photo' field exists, it uses the default photo also held in storage)

[GEN-46] Set Detail for setter clicking on a climb

---

trk/src/Screens/CompRanking/index.js

- Breaking ties by # of attempts
-> tested, it works. Though, it does what it is supposed to do, and shows how some further tweaking w/ James is necessary. E.g., a tie in points where one participant has completed more climbs than the other but has more # of attempts on each is ranked lower than someone who has completed fewer climbs but with fewer attempts.
Obviously, there should be more than just # attempts to break ties.

[GEN-195] Tie Break

---

trk/src/Components/ClimbItem.js
trk/src/Screens/ClimbDetail/index.js

ONLY FOR CLIMBERS: commercial climbs showed 'Loading...' upon read or navigation from profile, now they display a default photo or the photo stored in the pathway if specified on climb document. 
N.B for routesetter view, this functionality was already implemented
**Before:**
**After:**

[GEN-337] Default setter photo and default or path-specific climb photo for climbDetail 

---

trk/src/Screens/SetDetail/index.js
trk/src/api/CommentsApi.js

Coded:
- Api to search a comments document by somefield
- used this api to sift through comments that have the same climb id as the climb being displayed on setdetail
- the explanation and rating for this comment are saved in an array
- the array of feedback is displayed if not empty, and if empty, it says no feedback

[GEN-303] Feedback displayed to routesetters on setdetail

---

trk/src/Navigation/AppNavigator.js
trk/src/Screens/ClimbDetail/index.js
trk/src/Screens/GlossaryDefinition/index.js
trk/src/api/DescriptorsApi.js

**In this PR:**
- creation of descriptors collection (each descriptor doc has 3 fields: the descriptor, the definition, and the photo to illustrate the definition)
- descriptors api created to get descriptors by some field,
- glossaryDefinition screen that displays the descriptor, definition and image
- navigation set up to be able to navigate to glossaryDefiniton from home and profile
- Display of clickable descriptors in climbdetail which navigate to glossaryDefinition

[GEN-393] Climb descriptors and glossary

---

trk/src/Screens/ClimbDetail/index.js
trk/src/Screens/Home/index.js

**Overview**
- navigation to climbDetail upon successful NFC climbID retrieval
- climbData retrieval in firestore and taps creation only occur after navigation (executed in climbDetail rather than home)
- fixes in state management of constants in climbdetail which are prop drilled from profile but no longer from home.
**This is what happens if you read a climb with no wifi/4G**

[GEN-318] Navigation to climbDetail upon successful NFC read even with no wifi

---

trk/android/app/build.gradle

The latest Android builds weren't uploaded to the Google Play Store. Strange.
I believe it is because I was only _**editing**_ the current Release (with new builds), instead of _**creating**_ a new one.
But.. 1) There was no 'create new release' button (had to discard the existing one, then one appeared), and 2) why.. editing doesn't edit? #GooglePlayConsoleThings

[Android Store Build Version Update]

---

trk/src/api/GymsApi.js

the issue was that the fetchGyms function in GymsApi did not return a promise, but it was being treated as if it did in ClimbInputData.

Crash Issue Resolve

---

trk/ios/Podfile.lock
trk/src/Screens/ClimbCreate/index.js
trk/src/Screens/ClimbDetail/index.js
trk/src/Screens/SetDetail/index.js

- Allows route setters to modify images of their set climbs
How is this implemented?
- 3 files changed: Create Form, Set Details, and Climb Details.
1. Create form: changes how climbs are stored in the firestore storage and in the firestore collection, by adding images to an array (each with an "id", and a "path"). This provides code flexibility to how we may display images in future improvements.
2. Set / Climb details: Changed the way images get retrieved, accounting for our previous way of storing images.
Worth noting: images are now stored in "climb_images/" instead of "climb_image/". This keeps all old images in the old folder, not conflicting with the new images.
- 3 images: before - edit form - after

[GEN-458] Image Edit Feature for Route Setter

---

trk/src/Screens/GymDaily/index.js

**Main Changes**
- calculated the values that were previously hardcoded data
- made sure to set climb ids (to allow for navigation  to climb detail with id as prop in a later PR)
- the data is calculated based on the active climbs set by that user (and is therefore personalised to that user)

[GEN-453] Calculating the dashboard data

---

trk/src/Components/ClimberProfile.js
trk/src/Screens/ClimbDetail/index.js
trk/src/Screens/GymDaily/index.js
trk/src/Screens/Home/index.js
trk/src/Screens/Home_Backend/HomeScreenLogic.js
trk/src/Utils/AuthContext.js

- Created a Delete Tap button on ClimbDetail.js (only appears for climbers, not routesetters)
- This locates the tap by id and adds 'archived: true' to the object
- Returns to the previous page and reloads it to reflect changes (useFocusEffect, tested  with Firebase)
- The tap is archived (archived: true property added in firestore), and can be still viewed in firestore. Appears like deletion to the user
For Climbers
Fore Routesetters

[GEN-204] Delete Tap functionality for Climbers

---

trk/src/Screens/ClimbDetail/index.js
trk/src/Screens/Home_Backend/HomeScreenLogic.js

- Adjusted the catch block with a boolean variable to track if reading or not (displays message accordingly, on manual canceling).
- When reading an unwritten tag, the app used to crash with an error saying "null property not defined". Fixed it by altering useeffect a bit to check for valid climbData, and only proceeding to rendering with valid data.
When cancelled
When no climb is written on the tag already

[GEN-478] Fixes to NFC read for manual cancelling and unwritten tag (ClimbDetail)

---

trk/src/Screens/TabScreens/Record/Backend/logic.js

Made stylistic changes to:
1. provide context to when tagging should be done (text above button)
2. make it easier to press on button (by moving it to the bottom of view)
**Android:**
**IOS:***

[GEN-500] Clarify when to tag 

---

trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Backend/analyticsCalculations.js
trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Frontend/index.js

In gym analytics, fixed the following calculation edge cases
- a climb w/ 0 taps was not taken into account to calculate 'least completed route'
- if multiple climbs had same number of taps and were the least or most completed route, code would break
Now:
- 0 taps is considered 'least' completed
- least and most completed route is now an array that can contain multiple routes, and only the first climb in array is displayed on gym analytics

[GEN-459] Least completed route calculation fix

---

trk/src/Actions/tapActions.js
trk/src/Reducers/tapReducer.js
trk/src/Screens/NavScreens/ClimbDetail/Backend/ClimbDetailLogic.js
trk/src/Screens/NavScreens/ClimbDetail/Frontend/index.js
trk/src/Screens/TabScreens/Record/Backend/logic.js
trk/src/reduxStore.js

- Accounted for role in tap creation (simply passing the variable for Climb Detail)
- For the cached taps, I stored the role and processed it alongside in the Redux Store
- Minor bug fix for the Error shown when there is no climb stored on the NFC tag (needed to put error.message instead of error)
- Altered some console.erorr calls to console.log for simplicity
- The only changes made in logic are in fetchClimbData (ClimbDetailLogic.js) and processClimbId (tapActions.js)

[GEN-203] Fixed setter tap creation (including redux cache)

---

trk/src/Components/SessionTapHistory.js

Taps with timestamps of different timezones (not UTC-5) caused the app to crash when navigating to climber profile

fixing error timestamp

---

trk/src/Actions/tapActions.js
trk/src/Screens/NavScreens/ClimbDetail/Backend/ClimbDetailLogic.js

Replaced `ClimbDetailLogic.js` and `tapActions.js`'s timestamp date format with `new Date()`.

[GEN-568] timestamp fix v2

---

trk/src/Components/SessionTapHistory.js
trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js

- The timestamp being used for sessions was erroneously the climb timestamp (only a single timestamp variable was being used in the climb object, so I had picked it).
- Now the timestamp correctly reflects the tap timestamp.

Fix for Session Timestamp

---

trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
trk/src/Screens/TabScreens/Record/Backend/logic.js
trk/src/api/TapsApi.js

- Sessions are now calculated using isSession start
- Active session climbs can be fetched with a single query based on timestamp (less time, no heavy processing)
- Expired sessions are paginated (5 for now, will be dynamically reloading 5 on bottom hit every time- NEXT PR)
- Climbs History is irrelevant now (all calculations can be done with sessions), will remove in next PR
- Have shown how the new mock session objects can be used @redpepper-nag (Record/Backend/logic.js)- First Tap in Session

Session Revamp (Top-down Approach)

---

trk/src/Components/SessionTapHistory.js
trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
trk/src/api/TapsApi.js

- Paginated sessions (5 load initially)
- As the user reaches the end of the screen, 5 more keep loading.
- All climbs are loaded initially, but this avoids passing through the entire loop when loading sessions every time.
- The new sessions are appended to the bottom of SessionTapHistory, for smoother loading (not reset)

Session Pagination Implemented

---

trk/src/Components/ListHistory.js
trk/src/Components/ListItemSessions.js
trk/src/Components/SessionItem.js
trk/src/Components/SessionTapHistory.js
trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js

- Grouped independent climbs into a session within SessionTapHistory, if not in the current session
- Is a touchable opacity. On touching, will be sent to a new screen (next PR)
- Image data is tied to the last climb (fetching logic, when the user adds a new image, the first image of the last climb will be changed)

Change in session appearance on Climber Profile

---

trk/assets/tagMessages.json
trk/src/Screens/TabScreens/Record/Backend/logic.js

- added a flag in local storage that allows to check FTU v returning user
- use this flag to set the FTU state
- removed one of the conditions of returning user and combined the messages in JSON file (reason - messaging was almost identical in both conditions)
- In next PR, will do the rest of the set state for the multiple conditions of returning user

[GEN-588] Message condition FTU v returning user logic

---

trk/src/Components/ClimbItem.js
trk/src/Components/Edit_Session.js
trk/src/Components/ListItemSessions.js
trk/src/Components/SessionDetail.js
trk/src/Components/SessionItem.js
trk/src/Components/SessionTapHistory.js
trk/src/Navigation/AppNavigator.js
trk/src/Screens/NavScreens/ClimbDetail/Backend/ClimbDetailLogic.js
trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
trk/src/api/TapsApi.js

- Sessions can now be accessed in a new Screen (they are updated when taps within them are deleted, take you back to Profile tab)
- Can see duration, media, basic stats (from Figma). Climbs can be added or removed within SessionDetail.js
- Sessions can be edited (Adding media, changing title, displayed climb). Even when the session header node is deleted, this info is passed on to other items in the session (immutable)
- Fixed some minor UI bugs
https://github.com/nagimonyc/trk-app/assets/75244191/a7edec55-bab1-4eaa-a826-658c3e8d6cad

[GEN-536] Editing capabilities for sessions

---

trk/src/Components/SessionDetail.js

- The timestamps were not being verified as Date objects, affecting the duration calculation.

Converted Timestamps to Date (Duration Corrected)

---

trk/src/Components/LineGraphComponent.js

- Set a Minimum 10px reverse margin, to create distance for other points (excluding first and last)

[GEN-852] Min Distance Set for Graph

---

trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Frontend/index.js

Filtering by set dropdown was hidden underneath data boxes on Gym Daily Summary for iOS
**Before**
**After**
**For android**

[GEN-875] Fix filter by set for ios

---

trk/src/Actions/tapActions.js
trk/src/Screens/TabScreens/Record/Backend/logic.js
trk/src/Screens/TabScreens/Record/Frontend/index.js
trk/src/api/TapsApi.js

- Count previous taps for the same user for a climb and add 1 to it for every  new tap.
- If it is == 1 (first tap), the record message shown, else a PLACEHOLDER.
- STILL NEED TO ACCOUNT FOR RECENT VIDEO LOADING AND A BETTER MESSAGE.

Messaging based on Tap History

---

trk/src/Navigation/AppNavigator.js

**Problem** :  the back button on community always navigated back to record (even when coming from collection)
**Solution** : added community to the collection stack with its own backtitle
N.B.: still correctly navigates back to record when coming from record
https://github.com/nagimonyc/trk-app/assets/126114238/a0ed3803-88d2-49ad-a8f3-13005bbe9d31

[GEN-997] Community Backward Navigation

---

trk/src/Navigation/AppNavigator.js

- changed the order of the routesetter tabs and renamed 'record' to 'scan' for routesetters

[GEN-999] RS Tab Revamp
