nagimonyc/trk-app

- trk/ios/Podfile.lock
> publish it

- trk/ios/Podfile.lock
- trk/package-lock.json
- trk/package.json
- trk/src/App.js
- trk/src/Components/SignInUpToggle.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Navigation/AuthNavigator.js
- trk/src/Screens/ClimbList/index.js
- trk/src/Screens/Home/index.js
- trk/src/Utils/AuthContext.js
- trk/src/api/ClimbsApi.js
- trk/yarn.lock
- Adding User details to climb creation form (user.email)
- Removing call for all existing climbs in database in ClimbsInputData (why was that there in the first place is a mystery)
- Renamed Authentication to SignInUpToggle, to make it clearer what it does
- Adding React Context file above App parent compo to make it accessible everywhere
> Linking User (setter) to climb form + adding userID in db for Climbs collection

- trk/ios/Podfile.lock
- trk/package-lock.json
- trk/package.json
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/ClimbDetail/index.js
- trk/src/Screens/Home/index.js
- trk/src/Screens/Profile/index.js
- trk/yarn.lock
- Created 3 tabs  for the climber view of the app (Home, Climb List, Profile)
> [GEN-154] Tabs4climbers

- trk/src/Screens/ClimbDetail/index.js
Climb detail now shows the grade and title as shown in figma. The photos (setter photo and climb photo) have placeholder shapes for now, will work on this in next PR
> [GEN-146] Climbdetail view

- README.md
mini PR, now we can copy and paste directly from README when dealing w/ npm start issues
> [GEN-96] Read me for dependency issues

- trk/ios/Podfile.lock
- trk/package.json
- trk/src/Screens/ClimbDetail/index.js
- trk/yarn.lock
<h1>pre-uploaded (in firebase storage) images are loaded onto climb detail screen by referencing their firestore storage bucket pathwway</h1>
> [GEN-148] Climb detail loads setter and climb photo from firebase storage

- trk/src/Components/SignInUpToggle.js
> [GEN-182] toggle with nyu color

- trk/src/Components/ClimbItem.js
- trk/src/Components/ListHistory.js
- trk/src/Components/ListItemContainer.js
- trk/src/Components/RankHistory.js
- trk/src/Components/RankItem.js
- trk/src/Components/TapHistory.js
- Created 2 new component files: ListHistory.js and ListItemContainer.js.
- They combine similar list aspects together, as reusable components in ClimbItem/TapHistory and RankItem/RankHistory.
> [GEN-235] created ListHistory.js and ListItemContainer.js to remove redundancy

- trk/src/Screens/ClimbList/index.js
Fixed scrollability of the form
> [GEN-236] Usability of climblist p1

- trk/src/Screens/ClimbDetail/index.js
- trk/src/Screens/ClimbList/index.js
remove setter field which is automatically filled with user's email
> [GEN-243] Usability of climblist p2

- trk/src/Screens/ClimbDetail/index.js
> [GEN-248] Fixed unscrollable and hidden climbdetail competition form on android

- trk/src/Components/SignIn.js
- trk/src/Components/SignUp.js
- Empty fields led to app crash on android
Visual of the fix:
> Fix which prevented Android App from being approved by Google Play Store

- trk/src/Components/ClimberProfile.js
- trk/src/Components/RankItem.js
- trk/src/Components/SetterProfile.js
- trk/src/Components/SignIn.js
- trk/src/Components/SignInUpToggle.js
- trk/src/Components/SignUp.js
- trk/src/Screens/ClimbList/index.js
- trk/src/Screens/CompRanking/index.js
- trk/yarn.lock
Added text color to Setter and Climber Profile Components, useEffect() to load recap ("Reload") on profile mounting.
> Added text color for android and recap load on mounting

- trk/src/Components/ClimbItem.js
- trk/src/Screens/ClimbList/index.js
> iOS Climb List View updates

- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/ClimbCreate/index.js
changed file name, import into nav, displayed name
-b7f7-477e-9f68-ce31ff4a6bfe)
> [GEN-334] Renaming ClimbList

- trk/src/Navigation/AppNavigator.js
> [GEN-330] Change of tab name from ranking to analytics

- trk/ios/Podfile.lock
- trk/src/Screens/ClimbCreate/index.js
- trk/yarn.lock
FYI, couldn't uncommit PodFile.lock and yarn.lock. Managed to perform this operation on another PR but it doesn't work here.
> [GEN-346] Make default value of Set to 'Commercial' instead of 'Competition'

- trk/android/app/build.gradle
- trk/ios/trk.xcodeproj/project.pbxproj
- trk/ios/trk.xcodeproj/xcshareddata/xcschemes/trk.xcscheme
- trk/package-lock.json
- trk/yarn.lock
This PR contains the necessary parameter adjustments required to submit the app to both the Android and Apple app stores.
> [GEN-372] [Apple&Android] App uploads

- trk/src/Components/SignUp.js
- trk/src/Screens/ClimbCreate/index.js
- trk/src/Screens/FeedbackForm/index.js
Timestamped the following document creations to help us with data analysis:
1. Climb document creation
2. User document creation
3. Feedback document creation
> [GEN-415] Timestamping

- trk/src/Components/SignIn.js
- trk/src/Components/SignInUpToggle.js
- trk/src/Components/SignUp.js
1. signin now appears as login
2. a prompt appears at the bottom of the login saying 'Don't have an account' just above the signup toggle
3. in signup the following errors are now explained 
- password too short
- email already in use
- invalid email format.
4. in login, the following error is now explained 
- invalid email or password
> [GEN-416] Login/signup cleanup

- trk/src/Screens/ClimbCreate/index.js
- trk/src/Screens/ClimbDetail/index.js
1. added a climb info field into write climb form
2. made sure the keyboard didnt cover the text input
3. displayed this info when available on climbdetail below share and comment button
N.B this works the same on android, didnt attach the screenshots cause identical
> [GEN-418] - Climb Info input and display

- trk/ios/Podfile.lock
- trk/ios/trk.xcodeproj/project.pbxproj
- trk/ios/trk.xcodeproj/xcshareddata/xcschemes/trk.xcscheme
version and build number + scheme changed from debug to release
> App release tings

- trk/ios/Podfile.lock
- trk/src/Components/SetterProfile.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/ClimbCreate/index.js
- trk/src/Screens/ClimbDetail/index.js
- trk/src/Screens/SetDetail/index.js
- trk/src/api/ClimbsApi.js
PR is enabling route setters to edit (update/archive) a climb.
> [GEN-423] Route Setter can edit climbs

- trk/src/Screens/SetDetail/index.js
l m a o
-------
resolve conflict for the win
> [Fix] Button tag missing from react-native import

- trk/src/Screens/ClimbCreate/index.js
- trk/src/api/GymsApi.js
**Overview**
1. Creation of GymsApi with function that retrieves all the gyms documents and saves their names and ids
2. Using GymsApi to render a list of all the gyms documents (showing the name in the form dropdown and saving the id of the gym as the key value pair of gym in a newly created climb document)
**iOS**
**Android**
> [GEN-450] Gym dropdown populated by gyms collection documents

- trk/android/app/build.gradle
- trk/ios/trk.xcodeproj/project.pbxproj
> [App Store Build]

- trk/android/app/build.gradle
- trk/ios/trk.xcodeproj/project.pbxproj
> [App Store Builds]

- trk/src/Components/SignIn.js
- trk/src/Components/SignInUpToggle.js
- trk/src/Screens/Home/index.js
- Implemented the forgot password feature with a link in the sign in component (simple 'Forgot Password?')
- This triggers an email from Firebase to the connected email, where the user can reset their password (tested, works).
> [GEN-269] Implemented forgot password feature

- trk/src/Screens/Home/index.js
- trk/src/Screens/Home_Backend/HomeScreenLogic.js
- Created a new folder (Home_Backend)
- Shifted all the backend functions (4 of them, used in Home.js) to Home_Backend/HomeScreenLogic.js
- Cleaned up unused imports and other lines
- Tested accessing climb details with the tap (worked).
> [GEN-462] Cleaned up Home.js by separating frontend and backend logic (new folder)

- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/DeveloperFeedbackForm/index.js
- trk/src/Screens/FeedbackForm/index.js
- Created a Developer Feedback button (every page, top right corner for accessibility)
- Created a Developer Feedback Component, similar to Climb Feedback
- Added text box, checkbox, and submit button as specified
- Creates an alert if empty field, and when submitted, returning to the page button was clicked on (tested with firebase).\
For climbers:
For routesetters (similar, part of navigation stack):
> [GEN-405] Added the developer feedback button to each component

- trk/src/Backend/analyticsCalculations.js
- trk/src/Screens/GymDaily/index.js
**Overview**
- creation of backend folder for functions
- creation of file in backend folder for data calculation functions (analyticsCalculations)
- migrated the 3 calculation functions from GymDaily Screen into backend analyticsFunction file
> [GEN-463] - Backend for Analytics functions

- trk/src/Components/ClimberProfile.js
- trk/src/Components/SetterProfile.js
- trk/src/Screens/Profile/index.js
- Altered CSS to make the profile Climb Stack like Home
> [GEN-487] UI Changes to Profile (Similar to Home)

- trk/src/Screens/ClimbDetail/index.js
- trk/src/Screens/ClimbDetail_Backend/ClimbDetailLogic.js
- Created a new backend folder and migrated code to ClimbDetailLogic.js.
- Frontend components retained in ClimbDetail, API calls and backend functions were moved.
> [GEN-490] Climb Detail Clean Up

- trk/src/Screens/SetDetail/index.js
- trk/src/Screens/SetDetail_Backend/SetDetailLogic.js
- Created a new backend folder and migrated code to SetDetailLogic.js.
- Frontend components retained in SetDetail, API calls and backend functions were moved.
> [GEN-491] Set Detail Cleanup

- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- Added a new `Record` tab in Navigation
- Created 2 files, front and backend in `Record` folder
- moved relevant functions from the previous Backend Logic implementation in `HomeScreenLogic.js`
> [GEN-497] New Record Tab

- trk/src/Components/ClimberProfile.js
- trk/src/Components/SetterProfile.js
- Added Hi 'user' + icon to the Setter and Climber Profile.
> [GEN-507] Greeting Text added to Profile page

- trk/src/api/ClimbsApi.js
- trk/src/api/TapsApi.js
- trk/yarn.lock
- Fetched taps and climbs in descending order with a filter (made firebase indices to support these calls).
> [GEN-495] Async ordering of taps

- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/Screens/TabScreens/Profile/Backend/SetterProfile.js
- trk/src/Screens/TabScreens/Profile/Frontend/index.js
- Created a Backend Folder in Profile
- Migrated the Climber and Setter Profile components to it (as they are only used within Profile)
> [GEN-466] Migrating climber and setter profile to profile backend

- trk/src/Components/SessionTapHistory.js
- trk/src/Screens/NavScreens/ClimbDetail/Frontend/index.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/yarn.lock
- Grouped Taps by 4 hour sessions in Climber Profile
- Made a new SessionsTapHistory.js component for this
- Altered color for Fetching Climb information in ClimbDetail (only UI change)
> [GEN-504] Climber Sessions Created

- trk/src/Actions/tapActions.js
- trk/src/Components/ClimbItem.js
- trk/src/Screens/NavScreens/ClimbDetail/Backend/ClimbDetailLogic.js
- Altered the tap timezone from UTC to EST during tap creation
- Allows for consistency in the Live Tracker and other sections of code
> Timezone change from UTC to EST

- trk/src/Screens/NavScreens/ClimbDetail/Frontend/index.js
- trk/src/Screens/TabScreens/Record/Backend/logic.js
Added alert message upon successful tagging to indicate climb (tap) is added to profile
> [GEN-501] Clarifying where taps go/recording of taps

- trk/src/Navigation/AppNavigator.js
The buttons were stacked on top of each other because of differences in positioning of titles in IOS and android 
before:
after:
> [GEN-528] Title and feedback IOS bug

- trk/src/Screens/NavScreens/DataDetail/Frontend/index.js
- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Frontend/index.js
fixing bug in gym daily and adding appropriate messaging for data detail
> [GEN-552] - Data Detail screen 'feature coming soon' msg

- trk/src/Components/SignIn.js
> Oauth Apple 

- trk/src/Screens/NavScreens/ClimbDetail/Frontend/index.js
delete tap button is red IOS and android
> Styling delete tap button IOS

- trk/android/app/build.gradle
- trk/ios/Podfile.lock
- trk/ios/trk.xcodeproj/project.pbxproj
- trk/ios/trk.xcodeproj/xcshareddata/xcschemes/trk.xcscheme
Created a new task 'folder' in our current project to store all App Store Updates
> [GEN-561] V2 App Store Updates

- trk/assets/tagMessages.json
Built the JSON file with different messages based on this scenario tree https://www.figma.com/file/BJb3PPKuZMuGp96DRxyDQk/Tagging-Prompts?type=design&node-id=0%3A1&mode=design&t=KzyCXzsLlX9naqrh-1
> [GEN-562] JSON file for varying tagging message

- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
**Overview**
1. Made top of profile page look 'social-media-esque' to make it more personal and familiar 
2. Did not calculate session total as this is dependent upon other PR
**Before**
**After**
> [GEN-563] Making Profile about YOU

- trk/src/Screens/TabScreens/Record/Backend/logic.js
Animated Nagimo Logo
https://github.com/nagimonyc/trk-app/assets/66965648/797fdf74-9b4d-4e6a-9d1b-2be20bd356cf
> [GEN-529] Logo Animation

- trk/assets/tagMessages.json
- trk/src/Screens/TabScreens/Record/Backend/logic.js
**Overview**
- hardcoded the conditions (FTU v returning, first climb of day...)
- tagging message displayed according to which condition is met
- in cases where multiple variations of messages exist for a single condition, one is randomly selected
- every time the user re-navigates to 'Record', the message is re-randomized 
https://github.com/nagimonyc/trk-app/assets/126114238/848cd20f-ba4a-4800-afd5-d10130fad0b2
> [GEN-556] Random tagging message according to condition

- trk/src/Components/ClimbItem.js
- trk/src/Components/SessionTapHistory.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
**Part 1**
- Added Animation for Tap (fade in, drops down), on recording a tap, Toasts to handle other cases (documented in code)
- Check it out button (leads to profile), and a timer for 15 seconds (starts flashing at 10 seconds to indicate closure)
- The lower view (Climbing Text and Button) move back up once it disappears
https://github.com/nagimonyc/trk-app/assets/75244191/e1dfae40-0d81-48ce-b4b1-c645220330df
**Part 2**
- Refactored Session creation logic to Climber Profile (Louise's Session PR completed now)
- The sessions are now passed into SessionTapHistory (ONLY PERFORMS DISPLAYING LOGIC)
- Some Minor UI changes (Padding, added text to ClimbItem in Profile, as navigation from record will not point to right climb)
- Drag down refresh supported, reload button removed …
> [GEN-531] Record Animations and Session Refactoring

- trk/src/Screens/TabScreens/Record/Backend/logic.js
- Fixed issue in PR merge (duplicate animated header reference)
> Update logic.js (Record Screen)

- trk/android/app/src/main/java/com/nagimo/Nagimo/MainActivity.java
- trk/functions/index.js
- trk/functions/package-lock.json
- trk/functions/package.json
- trk/index.js
- trk/package-lock.json
- trk/package.json
- trk/src/Actions/tapActions.js
- trk/src/Components/ClimbItem.js
- trk/src/Components/ListHistory.js
- trk/src/Components/ListItemContainer.js
- trk/src/Components/SessionTapHistory.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Utils/AuthContext.js
- trk/src/api/TapsApi.js
- trk/yarn.lock
- Altered how sessions are created (6 hours, activated when a climb is logged)- DOCUMENTATION IN CODE
- Highlighted first item of current session.
- Session objects have not been creeated yet (Next PR)
- Shift from active -> expired session cannot be logged as sessions are temporary objects created with climbs when profile is clicked. (PUSH NOTIFICATIONS WILL NOT WORK, need to think of an alternative)
https://github.com/nagimonyc/trk-app/assets/75244191/b6b67e10-79bc-437f-b4f7-25a28d03fbf3
> [GEN-539] Active session created

- trk/src/Components/ListHistory.js
- trk/src/Components/SessionDetail.js
- trk/src/Components/SessionGraph.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- Created a SessionGraph component thats builds the graph from climbs input.
- Corrected how the session duration is calculated (tapTimestamp, was erronoeously just timestamp).
> [GEN-596] Session Graph Added, Duration Corrected

- trk/src/Components/ClimberPerformance.js
- trk/src/Components/Edit_Session.js
- trk/src/Components/SignIn.js
- trk/src/Components/SignUp.js
- trk/src/Components/UserEdit.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/LiveClimbTracker_Backend/LiveClimbTrackerLogic.js
- trk/src/Screens/NavScreens/GlossaryDefinition/Backend/GlossaryDefinitionLogic.js
- trk/src/Screens/TabScreens/GymAnalytics/CompRanking/Frontend/index.js
- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Backend/analyticsCalculations.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/Screens/TabScreens/Profile/Backend/SetterProfile.js
- trk/src/api/UsersApi.js
- Created a username alongside Account Creation.
- On Profile Page, Profile Pic (or email's first letter shows) along with username.
- There's a small edit icon to lead to the editing page (can click on profile pic circle).
- Can alter username and profile pic (username must be unique!)- CHECK IMPLEMENTED.
- Minor fix to Session Title Processing (trimmed the string, but is a TRIVIAL change).
https://github.com/nagimonyc/trk-app/assets/75244191/05b8df95-0211-4533-bc59-7d2ea1f25c8f
> Profile Editing Implemented, Usernames Created (Unique)

- trk/src/Screens/NavScreens/ClimbDetail/Backend/ClimbDetailLogic.js
- trk/src/Screens/NavScreens/ClimbDetail/Frontend/index.js
- removed share button and associated backend functions from climb detail
> [GEN-638] removed share button from individual climbs

- trk/src/Components/SessionItem.js
- modified `session item` by adding space for "climbed with" and "share performance"
> [GEN-644] share button v1 w/ placeholder text

- trk/src/Components/SessionDetail.js
- trk/src/Components/SessionItem.js
- trk/src/Components/UserSearch.js
- Tagged users' profile pics now appear in SessionItem (in the Profile, for the session).
- They also appear in Session Detail and while searching for users to tag.
> Tagged Users (UI Update)

- trk/src/Components/SessionTapHistory.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/api/TapsApi.js
- Added Tagging to Active Session.
- Displays number of people tagged, and usernames in a list format (can remove).
- UserSearch Component used
https://github.com/nagimonyc/trk-app/assets/75244191/7715b018-7d1b-49d6-9132-8cf61cc20a57
> Added tagging to Active Session (Like Session Editing)

- trk/package-lock.json
- trk/src/Screens/TabScreens/Follow/Backend/FollowPage.js
- trk/yarn.lock
> Autofocus fix

- trk/src/Components/UserEdit.js
- Updated username under the Nagimo Code (QR)
> Updated Username under the QR code

- trk/src/Components/SessionDetail.js
- trk/src/Components/SessionItem.js
- Placed the text inside a view.
> Fixed the Tagged User Circle (IOS)

- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- Nested the function in try-catch
- Only adds climb to firebase if nfc tap is created (otherwise it would create 2 documents)
- Tested as User (works well)
> [GEN-633] Fixed Create Climb

- trk/src/Components/UserSearch.js
- trk/src/Screens/TabScreens/Follow/Backend/FollowPage.js
- The search results are updated as the user types
https://github.com/nagimonyc/trk-app/assets/75244191/b9e03411-5332-487a-95e3-64aa12f81a95
> Real time Query updates for Follow

- trk/src/Actions/tapActions.js
- trk/src/Components/Edit_Session.js
- trk/src/Components/ListHistory.js
- trk/src/Components/SessionDetail.js
- trk/src/Components/SessionItem.js
- trk/src/Components/SessionTapHistory.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/api/SessionsApi.js
- trk/src/api/TapsApi.js
- tapActions and Record/Backend/logic were changed to create a new Session or update the Current session.
- ListHistory was changed to remve reversing the list (is now fetched from firebase in order).
- New SessionsApi created and TapsApi updated to remove unused functions.
- SessionsTapHistory updated to allow tagging the current session.
- SessionDetail, Edit_Session updated to deal with the new data (they load data independently now so can implement future reloading).
- Session Item loads faster as only required data is passed in (Session Collection Object data ONLY!).
https://github.com/nagimonyc/trk-app/assets/75244191/8f4c6e98-ef66-48a0-9e29-fc1767db7158
> [GEN-660] Session Revamp (New Collection)

- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/LiveClimbTracker/index.js
- trk/src/Screens/NavScreens/DataDetail/Frontend/index.js
**Overview**
- fixed the dashed line not rendering on ios (quick fix) 
- rendered the heatmap on datadetail of heatmap (RS dashboard)
- removed the heatmap from top bar
https://github.com/nagimonyc/trk-app/assets/126114238/a3d663f6-6e09-42da-88d4-4e2118d3082a
> [GEN-665] Moving heatmap to RS dashboard

- trk/android/app/src/main/AndroidManifest.xml
- trk/ios/trk/Info.plist
- trk/package-lock.json
- trk/package.json
- trk/src/Components/SessionItem.js
- trk/src/Screens/NavScreens/ShareSession/Frontend/index.js
- trk/yarn.lock
- Added Session Duration to the Image
- Can save it/ share it (No message, for now- CHANGE IN ANOTHER PR)
- Permissions Updated
https://github.com/nagimonyc/trk-app/assets/75244191/294565c4-9a5d-4aaf-8096-4e4f4f33115c
> [GEN-624] Permissions and Functionality to Save the Session Image Locally/ Share it

- trk/src/Screens/LiveClimbTracker/index.js
- trk/src/Screens/LiveClimbTracker_Backend/LiveClimbTrackerLogic.js
- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- trk/src/api/ClimbsApi.js
- trk/src/api/SetsApi.js
- Sets can now be created within Climbs (Old ones, and Custom names- makes a new Set Item).
- Sets are updated alongside climbs (deletion, updated set)- COMPLETELY FLEXIBLE.
- Filtering on the Live Climb Tracker is now done by set too.
> [GEN-666] Sets Created (Custom), and Filtering By Set

- trk/src/Navigation/AppNavigator.js
- Commenting out Home and Follow
> [GEN-759] Hide Home & Follow

- trk/src/Screens/NavScreens/ClimbDetail/Frontend/index.js
- trk/src/Screens/NavScreens/FeedbackForm/Frontend/index.js
**Overview**
- subheading for each data
- setter circle smaller
- feedback button at top
- info and photo switched order
- EXTRA: gradeCircle changed in feedback form for consistency purposes
**BEFORE**
**AFTER**
> [GEN-752] Redesigning climbDetail

- trk/package-lock.json
- trk/package.json
- trk/src/App.js
- trk/src/Components/SignInUp.js
- trk/src/Navigation/OnboardingNavigator.js
- trk/src/Screens/NavScreens/Onboarding/Front/onboarding.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide1.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide2.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide3.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide4.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide5.js
- trk/yarn.lock
- isNewUser was never created on Login (Normal/Google), so fixed it
- Minor fixes to make the App run (imports, names, etc)
- Package name issues
> Fixed the PR merges

- trk/src/Screens/NavScreens/FeedbackForm/Frontend/index.js
- Changed text color in the SegmentedControl to black, and active text color to white. 
- The original white color was barely visible.
> Feedback Form Visibility (Android)

- trk/src/Components/SessionTapHistory.js
- trk/src/Components/SignInUp.js
- trk/src/Screens/TabScreens/Record/Backend/logic.js
- Removed Active Session Tagging.
- Removed "No Active Session".
- Minor UI changes (top padding to Sign In/Up page, marginTop when no NFC/not Activated).
- Both features retained (false added, for now- WON'T RENDER)
> [GEN-760] Decluttered Profile

- trk/src/Components/SessionDetail.js
- Matched SessionDetail UI to Figma.
- Session Graph will be altered in another PR.
- ELEVATION is missing, NO HEIGHT VARIABLE IN CLIMBS. (NEXT PR)
https://github.com/nagimonyc/trk-app/assets/75244191/6d5b1a1d-d4d2-4688-8c6b-6f3eae6268d2
> [GEN-779] SessionDetail Revamp (No Graph)

- trk/src/Screens/NavScreens/DeveloperFeedbackForm/Frontend/index.js
- trk/src/Screens/NavScreens/FeedbackForm/Frontend/index.js
- Buttons set to IOS style (Louise's PR)
> [GEN-801] UI Changes (Buttons)

- trk/src/Components/LineGraphComponent.js
- trk/src/Components/OnboardingModal.js
- trk/src/Components/SessionDetail.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide1.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide2.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide3.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide4.js
- trk/src/Screens/NavScreens/Onboarding/Front/slide5.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- trk/src/api/SessionsApi.js
- Made the Session Graph
- Line Graph, Area Higglighted, Highest and Lowest Climbs are Marked (One for each of those levels)
- UI issues with Onboarding fixed (Android)- NO COLOR FOR TEXT (Defaults to white)
- Platform OS issues (Wrong library imported earlier, now works)
- Progress Tab Added (Weekly Climbs)
> [GEN-771] Session Graph Created

- trk/src/Components/SessionDetail.js
- trk/src/Components/Settings.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/NavScreens/ShareSession/Frontend/index.js
- Final UI changes for Climbers
- Delete Button Red, Sign Out is App Theme (Orangeish)
- Save and Share Aligned Properly
- Feedback button made smaller (as per figma), and "Beta" added to header
> Beta Added, Feedback Smaller

- trk/src/Components/SignInUp.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Backend/analyticsCalculations.js
- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Frontend/index.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- Altered Header UI for Setter Specific Pages (Feedback, Beta)- PREVIOUS PR (continued)
- Now Dashboard is Filtered By Set (Added a dropdown, but is useless as 'Commercial' is the only set)
- NO FUNCTIONALITY ON DROPDOWN for now (previous point)
- This page needs better UI (loading, and so on)- FUTURE PR
> [GEN-816] Setter Fixes

- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/NavScreens/DeveloperFeedbackForm/Frontend/index.js
- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- trk/src/Utils/AuthContext.js
https://github.com/nagimonyc/trk-app/assets/66965648/25e873b8-f2dc-41b9-8f7a-9eb43cb14131
> [GEN-821] onboarding inside feedback

- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
fixed bug that prevented writing tags on ios
> Bug Fix - Create Climb on iOS was failing

- trk/ios/Podfile.lock
- trk/ios/trk/AppDelegate.mm
- trk/ios/trk/Info.plist
- trk/ios/trk/trk.entitlements
- trk/package.json
- trk/src/Components/SignInUp.js
- trk/yarn.lock
> [GEN-608] Google/Apple Auth

- trk/src/Components/LineGraphComponent.js
- trk/src/Components/SignInUp.js
- trk/src/Screens/NavScreens/DeveloperFeedbackForm/Frontend/index.js
- Color of Text in Help set to 'black'
- Bug fix for one tap in Session/ Progress
- Bug Fix for Apple Oauth
> Help UI, Progress and Apple Oauth Bugs Fixed

- trk/src/Components/LineGraphComponent.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- trk/src/Utils/AuthContext.js
- trk/yarn.lock
- Fixes isNewUser state updates
- UI for Session Graph absence
> SessionGraph Fix, Login Bug

- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Backend/analyticsCalculations.js
- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Frontend/index.js
- Z Index Increased for visibility of dropdown.
- All Sets in a Gym visible now.
- Selection dynamically changes stats (SLOW- NEED TO OPTIMIZE IN ANOTHER PR).
> [GEN-834] Corrected Filtering for Analytics

- trk/src/Components/SessionDetail.js
- trk/src/Components/SessionItem.js
***Changes***
- session duration calculated in mins
- shown as minutes in:
1. sessionItem
2. sessionDetail
3. shareSession
> [GEN-851] Session duration in minutes

- trk/src/Components/Settings.js
> [GEN-869] NYU tryouts toggle added to settings

- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Backend/analyticsCalculations.js
- trk/src/Screens/TabScreens/GymAnalytics/GymDaily/Frontend/index.js
> [GEN-836] Climb ID added to document

- trk/src/Screens/NavScreens/ClimbDetail/Frontend/index.js
- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- UI updates to make Witness input field viewable when selected
- Centered titles
(*) `ClimbCreate` hasn't been touched. Only beautifying/indentation changed are applied
> Weekend comp updates

- trk/src/Components/SessionDetail.js
Calculation=  number of climbs * 4m
> [GEN-867] Calculating elevation

- trk/src/Screens/NavScreens/ShareSession/Frontend/index.js
- trk/yarn.lock
- Added Google Analytics trackers to Share and Save in Share Session (Will retain the same page for the collectibles, so did this, archived the one for edit session)
> [GEN-877] Added Analytics to Share and Save

- trk/package-lock.json
- trk/package.json
- trk/src/Components/Settings.js
- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- trk/yarn.lock
- Added RIC Sliders (default to 2- NEED TO DECIDE).
- Added to Climb Object on Creation and Updates.
> [GEN-900] RIC Implemented for Climb Create

- trk/android/app/src/main/AndroidManifest.xml
- Altered the manifest file, to make the app Portrait only on Android.
> [GEN-899] Screen Lock Fix (Android)

- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/api/CommentsApi.js
First pass of developing the Profile page. Lacks stats coverage for `Climb Found Count` and lifetime `Best Effort`. Also, needs a visual fix for the icon.
**Full-View**:
**Graph-View**:
> [GEN-926] profile v1

- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
Profile Done.
Modifications/Missing:
- Missing `Climbs Found` (in **Stats**, pending collection screen creation)
- Altered Climbing Sessions (this week) -> Climbing Sessions (Total). Didn't seem logical to only do it by week + didn't have data at hand to compute
> [GEN-930] Profile stats (except Climb Founds)

- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/api/SetsApi.js
- Sets were not specific to any Gym.
- Altered SetsApi to accept Gym ID and filter accordingly.
- Profile colors were not visible on Android, and no Settings Button (corrected both).
> Set Fix, Profile Visibility

- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- UI fixes to record for better visibility and Component rearrangement.
- Fixed Image Circle Placement within text.
> Record Card Visibility

- trk/src/Screens/NavScreens/Community/Frontend/index.js
Creating the foundation for the upcoming Community Screen PRs
> [GEN-942] community screen prep

- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- Update the parameters of the Card Component on Tapping.
- STILL NEED TO HARD CODE COLOR, IMAGE IN THE DB FOR CLIMBS.
- STILL NEED TO MAKE IT A TOUCHABLE OPACITY.
- Removed the disappearing animation to ? later, do we want it?
> Updating Card Component on Tapping

- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
https://github.com/nagimonyc/trk-app/assets/75244191/f3816b13-7c5e-4e50-adf8-6648b39180f8
> Animation Added Again (15s)

- trk/src/Components/Collection.js
- trk/src/Components/TapCard.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- Removed autoplay from mini-videos (on record and tapcard).
- Collection is cached for every subsequent use.
- Negative Search count fixed (Math.max(, 0))
> Autoplay Removed

- trk/src/Components/Collection.js
- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- Commented Out Session Logic (Loads Faster)
- zIndex of Badge Animation Updated
https://github.com/nagimonyc/trk-app/assets/75244191/cb202b92-467a-4820-8dd8-154fc2511923
> Profile Loading Fixed

- trk/src/Components/Collection.js
- Scrolling disabled for collection items under Grade.
> Scrolling Disabled

- trk/src/Components/Collection.js
- trk/src/Navigation/AppNavigator.js
> [GEN-951] Fixed scrolling, lines, "!", & extra tab rename

- trk/src/Components/Collection.js
- trk/src/Components/Community.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
- Close Button at the Bottom of the Modal
- Clicking Outside the Modal shuts it.
- [UPDATE] Making videos private added
- [UPDATE] Close Button Placed at the Bottom Right
https://github.com/nagimonyc/trk-app/assets/75244191/7ab90975-5695-4eea-a991-1d0c30d56848
> Close Button and Modal Click

- trk/src/Components/Collection.js
- trk/src/Components/UserEdit.js
Profile edit page updated:
- Prevent keyboard from hiding view on iOS
Collection tab:
- minor visual improvements
> [build update] Profile Edit + Collection tab visual

- trk/src/Components/TapCard.js
- Added to selection logic (sooner)
> Hotfix Upload Animation

- trk/src/Components/TapCard.js
- implementation could easily be improved, but it works.
Will improve/refactor if i have time at the end of the week
> live upload %

- trk/functions/index.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/NavScreens/Notification/Frontend/index.js
- trk/yarn.lock
bell icon doesn't work on iOS, as always 😎
Video is too long, can't upload unfortunately
> [GEN-1012] Notification (bell icon, count updates, onclick refresh, notification)

- trk/functions/index.js
- trk/package-lock.json
- trk/package.json
- trk/src/Components/RoomsScreen.js
- trk/src/Components/UsersScreen.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- trk/src/api/UsersApi.js
- trk/tsconfig.json
- trk/yarn.lock
- Added property bubbles
- Added, updated along with climb
- Loaded in on edit (fixed another api bug, adding movement gym ID)
- Dummy Message Component (ignoreUndefinedProperties Error)
https://github.com/nagimonyc/trk-app/assets/75244191/cfba7e47-d296-4748-8002-70f530ab2ee2
> [GEN-977] Dummy Message Component, Create Climb Full

- trk/assets/tagMessages.json
- trk/src/Screens/TabScreens/Record/Backend/logic.js
- trk/src/Screens/TabScreens/Record/Frontend/index.js
##Summary
1. idle climbCard has different messaging for RS 
2. Messaging above nfc button is different for RS 
3. Card gets filled with climb info (not tap info) for RS
4. Climb card is not clickable for RS because requires tap information to be passed into modal which is not available for RS
##Video
https://github.com/nagimonyc/trk-app/assets/126114238/5c207106-68e0-4068-910d-051794efaa0a
> [GEN-978] Scanning for RS

- trk/src/Components/UserEdit.js
- trk/src/Screens/TabScreens/Profile/Backend/SetterProfile.js
- trk/src/api/ClimbsApi.js
- Bio Feature Added
- Climbs are Shown as in Collection
- Metrics are computed EXCEPT climbers_watching and your_hold_color (UNSURE OF HOW TO CALCULATE)
- The type of climbs is the maximum property picked across climbs set (eg-Crimpy)
- TapCard Modal is NOT PRESENT!
https://github.com/nagimonyc/trk-app/assets/75244191/702065c3-9cea-4aa3-9a3e-1477e09af65a
> [GEN-980] Setter Profile

- trk/src/Navigation/AppNavigator.js
> [GEN-1032] 

- trk/functions/index.js
- trk/src/Components/Community.js
- trk/src/Screens/NavScreens/Notification/Frontend/index.js
Works as intended. Notification opens climber's beta video as Modal.
**Issue**: Must remove all notification documents without `video` field.
> [GEN-1029] Notification now open associated beta video

- trk/ios/Podfile.lock
- trk/src/Components/Collection.js
- trk/src/Components/Community.js
- trk/src/Components/TapCard.js
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/TabScreens/Profile/Backend/SetterProfile.js
- trk/yarn.lock
Works with previous video implementation. No videos are lost
> [GEN-1021] setter label

- trk/src/Components/Collection.js
- trk/src/Components/TapCard.js
All climbs appear. Climbs with videos have a green border.
> Refactor climb tile and tap card components

- trk/src/Components/Collection.js
> Gym filtering

- trk/src/Components/Collection.js
> unblur all cards

- trk/src/Components/Collection.js
- trk/src/Components/TapCard.js
- trk/yarn.lock
- Fixed Video Uploading (ONLY TO COMMUNITY)
- The issue is that all tap cards have been unlocked so there is no tap for us to put a video on.
- Fixed it to upload to community (CAN RETRIEVE IN MINE BASED ON USER ID LATER)
- Minor UI Changes in Collection (Dropdown was earlier over the TapCard Modal)
> Video Uploading Fixed

- trk/src/Components/Collection.js
- trk/src/Components/TapCard.js
> Revert "New card modal design"

- trk/src/Screens/TabScreens/ClimbCreate/Frontend/index.js
- Added it to preloading, adding, and updating of sets
> Create Climb With Gowanus Sets

- trk/src/Components/Collection.js
> z-index fix

- trk/src/Screens/NavScreens/Pay/Frontend/index.js
- trk/yarn.lock
> [GEN-1085] UI Design (part 1)

- trk/src/Components/Collection.js
- trk/src/Navigation/AppNavigator.js
removed `Record` for `Climbers`. No longer needed.
> [GEN-1080] removed record

- trk/android/app/build.gradle
- trk/android/app/src/main/AndroidManifest.xml
- trk/android/build.gradle
- trk/functions/index.js
- trk/functions/package-lock.json
- trk/functions/package.json
- trk/package-lock.json
- trk/package.json
- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/NavScreens/Pay/Frontend/index.js
- trk/yarn.lock
- Stripe Payment Added (GPay supported BUT NEEDS TO BE APPROVED BY GOOGLE)
- Main change is compileSDK (34) and minSDK (24), as required byb Stripe.
- New Firebase Function (paymentSheet), as API endpoint for CUSTOM AMOUNTS (future changes supported).
- Duplicate payments Avoided by disabling button.
- Still in TEST MODE (need to remove testing from GPay and change PUBLISHABLE KEY (client side), and firebase function parameters)
https://github.com/nagimonyc/trk-app/assets/75244191/6f31b667-1803-4670-ba57-ce15776900f7
> [GEN-1071] Stripe V1

- trk/src/Screens/NavScreens/Pay/Frontend/index.js
- Google Play testEnv: false
- Loading Flag when Payment Initializing
> Minor Logic Changes (Stripe)

- trk/src/Navigation/AppNavigator.js
- Messaging removed for RS.
- Feedback changed to Nagimo+ for climbers.
> [GEN-1087] Removed Messaging, Feedback

- trk/src/Screens/NavScreens/Pay/Frontend/index.js
> Apple Pay Integration

- trk/src/Screens/NavScreens/Pay/Frontend/index.js
commented out everything except simple view/text to state "coming soon".
+ google analytics tracker on page load
> Button2nowhere2

- trk/src/Navigation/AppNavigator.js
> [GEN-1112] share fix

- trk/src/Components/Collection.js
- trk/src/Components/Community.js
- trk/src/Components/New_Share.js
- Gym and collection data is selected based on Last Selected Gym (to populate and then reload).
- Share now has Videos.
- "Mine" Bug fixed (earlier your videos would show for all climbs, restricted to a climbId now).
> Default Loading Changed to Cached, Share Functionality, Bugs

- trk/src/Navigation/AppNavigator.js
- trk/src/Screens/TabScreens/Membership/Frontend/index.js
> [GEN-1128] Membership UI

- trk/src/Screens/TabScreens/Profile/Backend/ClimberProfile.js
Only loads user profile image now. so almost instant loading time
> [GEN-1186] profile optimization

- trk/functions/index.js
- Stripe JS Function (Published, just updating code)
> JS Function for Stripe

- trk/functions/index.js
> changed payment mode
